// Code generated by protoc-gen-go.
// source: grpcgo.proto
// DO NOT EDIT!

/*
Package trygrpcgo is a generated protocol buffer package.

It is generated from these files:
	grpcgo.proto

It has these top-level messages:
	Person
	SendPersonReply
*/
package trygrpcgo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Name   string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id     int32                 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Email  string                `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phones []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phones" json:"phones,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_PhoneNumber struct {
	Number string           `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Type   Person_PhoneType `protobuf:"varint,2,opt,name=type,enum=trygrpcgo.Person_PhoneType" json:"type,omitempty"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type SendPersonReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *SendPersonReply) Reset()                    { *m = SendPersonReply{} }
func (m *SendPersonReply) String() string            { return proto.CompactTextString(m) }
func (*SendPersonReply) ProtoMessage()               {}
func (*SendPersonReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Person)(nil), "trygrpcgo.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "trygrpcgo.Person.PhoneNumber")
	proto.RegisterType((*SendPersonReply)(nil), "trygrpcgo.SendPersonReply")
	proto.RegisterEnum("trygrpcgo.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for PersonSender service

type PersonSenderClient interface {
	SendPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*SendPersonReply, error)
}

type personSenderClient struct {
	cc *grpc.ClientConn
}

func NewPersonSenderClient(cc *grpc.ClientConn) PersonSenderClient {
	return &personSenderClient{cc}
}

func (c *personSenderClient) SendPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*SendPersonReply, error) {
	out := new(SendPersonReply)
	err := grpc.Invoke(ctx, "/trygrpcgo.PersonSender/SendPerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PersonSender service

type PersonSenderServer interface {
	SendPerson(context.Context, *Person) (*SendPersonReply, error)
}

func RegisterPersonSenderServer(s *grpc.Server, srv PersonSenderServer) {
	s.RegisterService(&_PersonSender_serviceDesc, srv)
}

func _PersonSender_SendPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonSenderServer).SendPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trygrpcgo.PersonSender/SendPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonSenderServer).SendPerson(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonSender_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trygrpcgo.PersonSender",
	HandlerType: (*PersonSenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPerson",
			Handler:    _PersonSender_SendPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("grpcgo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xd7, 0xad, 0xab, 0xf6, 0x6d, 0xcc, 0xfa, 0x10, 0x09, 0x15, 0x61, 0xf4, 0x34, 0x10,
	0x2a, 0x54, 0x3c, 0x7a, 0x11, 0x06, 0x8a, 0xd6, 0x8e, 0x28, 0x7a, 0xee, 0x5c, 0xa8, 0x83, 0x35,
	0x09, 0x69, 0x3d, 0xf4, 0x9f, 0x17, 0xd3, 0xa4, 0x9b, 0x43, 0xf1, 0xf6, 0xbd, 0xaf, 0xbf, 0xf7,
	0xbd, 0x8f, 0x06, 0xc6, 0x85, 0x92, 0xef, 0x85, 0x88, 0xa5, 0x12, 0xb5, 0x40, 0xbf, 0x56, 0x8d,
	0x35, 0xa2, 0x2f, 0x07, 0xbc, 0x05, 0x53, 0x95, 0xe0, 0x88, 0xe0, 0xf2, 0xbc, 0x64, 0xc4, 0x99,
	0x3a, 0x33, 0x9f, 0x1a, 0x8d, 0x13, 0xe8, 0xaf, 0x57, 0xa4, 0xaf, 0x9d, 0x21, 0xd5, 0x0a, 0x4f,
	0x60, 0xc8, 0xca, 0x7c, 0xbd, 0x21, 0x03, 0x03, 0xd9, 0x01, 0xaf, 0xc1, 0x93, 0x1f, 0x82, 0xb3,
	0x8a, 0xb8, 0xd3, 0xc1, 0x6c, 0x94, 0x9c, 0xc7, 0xbb, 0x03, 0xb1, 0x0d, 0x8f, 0x17, 0xed, 0xf7,
	0xa7, 0xcf, 0x72, 0xc9, 0x14, 0xed, 0xe0, 0xf0, 0x15, 0x46, 0x7b, 0x36, 0x9e, 0x82, 0xc7, 0x8d,
	0xea, 0x1a, 0x74, 0x13, 0x5e, 0x82, 0x5b, 0x37, 0x92, 0x99, 0x16, 0x93, 0xe4, 0xec, 0x9f, 0xec,
	0x17, 0x8d, 0x50, 0x03, 0x46, 0x17, 0xe0, 0xef, 0x2c, 0x04, 0xf0, 0xd2, 0xec, 0xf6, 0xfe, 0x71,
	0x1e, 0xf4, 0xf0, 0x10, 0xdc, 0xbb, 0x2c, 0x9d, 0x07, 0x4e, 0xab, 0xde, 0x32, 0xfa, 0x10, 0xf4,
	0x35, 0x7c, 0xf4, 0xcc, 0xf8, 0xca, 0x46, 0x51, 0x26, 0x37, 0x0d, 0x12, 0x38, 0x28, 0x59, 0x55,
	0xe5, 0xc5, 0xf6, 0x5f, 0x6c, 0xc7, 0x24, 0x85, 0xb1, 0x05, 0xdb, 0x15, 0x5d, 0xed, 0x06, 0xe0,
	0x67, 0x19, 0x8f, 0xff, 0x54, 0x0b, 0xc3, 0x3d, 0xeb, 0xd7, 0x99, 0xa8, 0xb7, 0xf4, 0xcc, 0x73,
	0x5c, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x11, 0x87, 0x21, 0x9e, 0x01, 0x00, 0x00,
}
